- public/index.html
- src/styles/App.styled.jsx
Підкючила шрифти в index.html
Додала розміри контейнерів для всих пристроїв
> add container&fonts

- package-lock.json
- src/components/Drinks/Drinks.jsx
- src/components/Drinks/Drinks.styled.jsx
- src/components/Drinks/DrinksItem.jsx
- src/components/Drinks/DrinksItem.styled.jsx
- src/views/DrinksPage/DrinksPage.jsx
add drinks page - title, drinks list, styles
> add drinks page

- package-lock.json
- package.json
- src/redux/auth/authOperations.js
- src/redux/auth/authSelectors.js
- src/redux/auth/authSlice.js
Віка, додала в залежності axios
написала операції, слайс та селектори
в операціях не вказала дефолтну url, коли скаже Денис, яку писати, то пропишу
в слайс в початоковий стан додала тему, про це казали на плануванні, а також у будь-якому випадку здійснення логАуту
> add auth redux

- src/components/Footer/Footer.jsx
- src/components/Logo/Logo.jsx
- src/components/Logo/Logo.styled.jsx
почала роботу над футером: створила лого + стилі
побачити не змогла свою роботу, тому що перед затягуванням собі main та створенням нової гілки сайт з гіта не запускався, Відповідно і в мене він не запустився. Робила наосліп
> add Logo+style

- src/components/Footer/Footer.jsx
- src/components/Footer/Footer.styled.jsx
- src/components/Footer/SocialMedia/SocialMedia.jsx
- src/components/Footer/SocialMedia/SocialMedia.styled.jsx
- src/components/Logo/Logo.styled.jsx
- src/components/SharedLayout/SharedLayout.jsx
> add socialMedia, intermediate stage

- src/components/App.jsx
- src/redux/drinks/drinksOperations.js
- src/redux/drinks/drinksSelectors.js
- src/redux/drinks/useDrink.js
Привіт. Відновів свій комонент PreviewDrinks
Також у редаксі створив у папці drinks додатково: drinksOperations.js, drinksSelectors.js 
Прописав запити для всіх сторінок. Покищо все закоментував те що не відає бекенд. 
Конда може вже корегувати кожен свій запит згідно з тим як прописав Денис.
Попередній URL до бази я вставив у drinksOperations
> Update PreviewDrinks Component + Redax/Drinks

- src/hooks/handlers.js
- src/hooks/useDrink.js
- src/redux/drinks/drinksOperations.js
- src/redux/drinks/drinksSlice.js
Додав ще handlers.js у hooks. Переніс ще туди свій useDrinks.js 
Також для всіх додав drinkSlice.js
> Correction redux

- src/components/FollowUs/FollowUs.styled.jsx
- src/components/Footer/Footer.styled.jsx
прибрала зміну фону іконок в соцмережах, задала висоту футера, виправила помилку в назві властивсті
> Subscribe form

- package-lock.json
- src/components/Footer/Footer.styled.jsx
- src/components/Footer/FooterCopyright/FooterCopyright.styled.jsx
- src/views/PrivacyPolicyPage/PrivacyPolicyPage.jsx
- src/views/PrivacyPolicyPage/PrivacyPolicyPage.styled.jsx
- src/views/TermsServicePage/TermsServicePage.jsx
add 2 new pages, a little styles
> add new pages

- src/components/Drinks/Drinks.jsx
- src/components/Drinks/DrinksItem.jsx
- src/components/DrinksSearch/DrinksSearch.jsx
- src/components/DrinksSearch/DrinksSearch.styled.jsx
- src/redux/filter/filterSelector.js
- src/redux/filter/filterSlice.js
- src/redux/filters/filtersOperations.js
- src/redux/filters/filtersSelector.js
- src/redux/store.js
- src/views/DrinksPage/DrinksPage.jsx
add filters redux (but not all the code, for the time being), debounce
> add filters redux

- package-lock.json
- src/components/DrinksSearch/DrinksSearch.jsx
- src/hooks/useFilters.js
- src/redux/filters/filtersOperations.js
- src/redux/filters/filtersSelector.js
- src/redux/filters/filtersSlice.js
- src/redux/store.js
> add redux/filters

- src/components/ButtonBack/ButtonBack.jsx
- src/components/ButtonBack/ButtonBack.styled.jsx
- src/components/ButtonBack/IconArrowLeft.jsx
- src/components/Footer/Footer.styled.jsx
- src/components/Footer/FooterCopyright/FooterCopyright.styled.jsx
- src/components/Forms/SubscribeForm/SubscribeForm.styled.jsx
- src/views/PrivacyPolicyPage/PrivacyPolicyPage.jsx
- src/views/PrivacyPolicyPage/PrivacyPolicyPage.styled.jsx
- src/views/TermsServicePage/TermsServicePage.jsx
style Policy and Terms page, add BackButton, a little bit style of footer
> style Policy and Terms page

- src/components/DrinksSearch/DrinksSearch.jsx
- src/hooks/useFilters.js
- src/redux/filters/filtersOperations.js
- src/redux/filters/filtersSelector.js
- src/redux/filters/filtersSlice.js
- src/views/DrinksPage/DrinksPage.jsx
added redux for filters (done!)
> add redux for filters

- src/components/PageTitle/PageTitle.jsx
- src/views/PrivacyPolicyPage/PrivacyPolicyPage.jsx
- src/views/TermsServicePage/TermsServicePage.jsx
додала маленькі зміни на PageTitle, для скрол ап на моїх сторінках.
Може комусь теж згодиться на інших сторінках
> scroll up 

- src/components/DrinksSearch/DrinksSearch.jsx
added ingredients selector with all the ingredients
> add ingredients selector

- src/components/Forms/SubscribeForm/SubscribeForm.jsx
- src/components/Forms/SubscribeForm/SubscribeForm.styled.jsx
Додала логіку для неактивної кнопки, GPT чат каже все вірно, але не працює
поки закину як є і буду шукати далі, в чому проблема
> try to make btn disable, not sucsses

- src/components/Drinks/Drinks.jsx
- src/components/Drinks/Drinks.styled.jsx
- src/components/DrinksSearch/DrinksSearch.jsx
- src/components/DrinksSearch/DrinksSearch.styled.jsx
- src/components/DrinksSearch/Select.jsx
- src/redux/drinks/drinksSlice.js
- src/redux/filter/filterSelector.js
- src/redux/filter/filterSlice.js
- src/views/DrinksPage/DrinksPage.jsx
all the search logic is done
added paginator, filter with 3 params, modified some redux slices
> add search logic

- src/components/Footer/Footer.jsx
- src/components/Logo/Logo.styled.jsx
- src/components/SharedLayout/SharedLayout.jsx
- src/components/ThemeToggler/ThemeToggler.jsx
- src/views/PrivacyPolicyPage/PrivacyPolicyPage.styled.jsx
Спробувала змінити кольори через пропси. На прайвесі та Термз змінилось. футер тепер проблемний, він не має змінюватись, а лого загальне і соц мережі теж, вони ма.ть змінюватись за умови. Поки нічого не працює, буду думать над цим
> first attempt update colors

- src/components/Modal/UserInfoModal/UserInfoModal.jsx
- src/hooks/useAuth.js
- src/redux/auth/authOperations.js
- src/redux/auth/authSlice.js
додала лише операцію та слайс, сама логіка в модалці ще не робоча
> add update operation

- src/components/FollowUs/FollowUs.styled.jsx
- src/components/Nav/Nav.styled.jsx
- src/components/PopularDrinks/PopularDrinks.jsx
- src/components/PopularDrinks/PopularDrinks.styled.jsx
Додала стилі в популярні напої. Не працює перенос карток в таблетці, пробувала і грід, і флекс. Не бачу, в чому проблема. Може вже голова не соображає. 
ВІд себе додала неоновий ховер на картки популярних коктейлів. Подивись, як тобі
> Popular drinks

- src/components/FollowUs/FollowUs.styled.jsx
- src/components/FollowUs/FollowUsAdd.jsx
- src/components/Footer/Footer.jsx
- src/components/Header/LogoHeder.jsx
- src/components/Logo/Logo.styled.jsx
додала зміну коліру в лого тексе, але вважаю це неправильно
Створила файл для FolloeUs, але ще не вносила туди зміни
Тому що в такому варіанті сенс перевикористання компонентів втрачено, бо ми по суті створюємо такий самий компонент і дублюємо стилі. Ще пошукаю рішення, якщо не знайду, доведеться дублювати компонент
> add color logo txt

- src/components/Drinks/DrinksItem.styled.jsx
- src/components/DrinksSearch/DrinksSearch.styled.jsx
- src/components/DrinksSearch/Select.jsx
> add dark/light styles

- src/views/DrinksPage/DrinksPage.jsx
- src/views/DrinksPage/DrinksPage.styled.jsx
> fix some styles
